Repository fourkitchens/quiltme-fe, pull requests merged in 2023-06, with the labels that each got.

#5 QUILTME-135: Bottom pop up
  package.json
  public/4k-people.jpg
  src/components/ui/01-atoms/background-pattern.jsx
  src/components/ui/02-molecules/bottom-banner.jsx
  src/components/ui/02-molecules/logo.jsx
  src/components/ui/02-molecules/page-footer.jsx
  src/components/ui/02-molecules/page-header.jsx
  src/img/4k-logo.svg
  src/img/4k-team.svg
  src/img/icons/close.svg
  src/img/icons/image-search.svg
  src/img/small-logo.svg
  src/pages/index.jsx
  src/theme/index.js
  yarn.lock
Labels: passes code review, passes functional review, passes design review, ready to merge

#6 Quiltme 149: Image grid & search box.
  next.config.js
  package.json
  src/components/ui/02-molecules/bottom-banner.jsx
  src/components/ui/02-molecules/image-controls.jsx
  src/components/ui/02-molecules/image-list.jsx
  src/components/ui/02-molecules/page-footer.jsx
  src/components/ui/02-molecules/page-header.jsx
  src/components/ui/02-molecules/search-bar.jsx
  src/components/ui/03-organisms/images-grid.jsx
  src/components/ui/03-organisms/page-footer.jsx
  src/components/ui/03-organisms/page-header.jsx
  src/components/wrappers/page-layout-wrapper.jsx
  src/hooks/use-media-query.js
  src/img/icons/image-search.svg
  src/img/logo.svg
  src/pages/_app.jsx
  src/pages/api/hello.jsx
  src/pages/index.jsx
  src/styles/Home.module.css
  src/styles/globals.css
  src/styles/lg-overrides.css
  src/theme/index.js
  tsconfig.json
  yarn.lock
Labels: passes code review, passes functional review, passes design review, ready to merge

#2 QUILTME-110: Add apollo config.
  .env.local.example
  package.json
  src/components/ui/01-atoms/animated-svg.jsx
  src/components/ui/02-molecules/bottom-banner.jsx
  src/components/ui/03-organisms/page-header.jsx
  src/components/wrappers/page-layout-wrapper.jsx
  src/graphql/user-submission.graphql
  src/lib/apolloClient.js
  src/pages/_app.jsx
  yarn.lock
Labels: passes code review, ready to merge

#7 Quiltme-143: Sidebar.
  package.json
  src/components/ui/01-atoms/button.jsx
  src/components/ui/01-atoms/full-button.jsx
  src/components/ui/01-atoms/icon-button.jsx
  src/components/ui/02-molecules/bottom-banner.jsx
  src/components/ui/02-molecules/image-controls.jsx
  src/components/ui/02-molecules/image-list.jsx
  src/components/ui/02-molecules/image-preview.jsx
  src/components/ui/02-molecules/search-bar.jsx
  src/components/ui/02-molecules/sidebar.jsx
  src/components/ui/03-organisms/images-grid.jsx
  src/components/ui/03-organisms/page-footer.jsx
  src/components/ui/03-organisms/page-header.jsx
  src/components/wrappers/page-layout-wrapper.jsx
  src/graphql/user-submission.graphql
  src/hooks/use-image-grid-columns.js
  src/styles/globals.css
  src/styles/lg-overrides.css
  src/theme/index.js
  yarn.lock
Labels: passes code review, passes functional review, ready to merge

#9 Quiltme-150: Adjusting autocomplete component.
  src/components/ui/02-molecules/image-preview.jsx
  src/components/ui/02-molecules/search-bar.jsx
  src/components/ui/03-organisms/images-grid.jsx
  src/components/wrappers/images-grid-wrapper.jsx
  src/context/submission.jsx
  src/graphql/search-user.graphql
  src/graphql/user-submissions.graphql
Labels: passes code review, passes functional review, ready to merge
